INTERACTIVE_SCENES = {
    "chapter_02_room": {
        "title": "Oren's Room",
        "objective": "Get dressed before leaving the room.",
        "required_actions": ["get_dressed"],
        "hotspot_order": ["dresser", "supplies", "meditation", "team_training", "door"],
        "hotspots": {
            "dresser": {
                "label": "Armor Stand",
                "icon": "!",
                "xpos": 0.63,
                "ypos": 0.55,
                "completes": "get_dressed",
                "hide_when_complete": True,
                "description": "Put on Oren's armor.",
            },
            "supplies": {
                "label": "Supply Pouch",
                "icon": "+",
                "xpos": 0.28,
                "ypos": 0.60,
                "completes": "take_supplies",
                "hide_when_complete": True,
                "description": "Take elixirs before training.",
            },
            "meditation": {
                "label": "Meditation",
                "icon": "*",
                "xpos": 0.45,
                "ypos": 0.68,
                "description": "Train inside Oren's mind.",
            },
            "team_training": {
                "label": "Team Drill",
                "icon": "**",
                "xpos": 0.58,
                "ypos": 0.70,
                "description": "Test ally and enemy team battle flow.",
            },
            "door": {
                "label": "Door",
                "icon": "->",
                "xpos": 0.88,
                "ypos": 0.43,
                "requires": ["get_dressed"],
                "blocked_message": "I should get dressed before I leave.",
                "description": "Step into the inn hallway.",
            },
        },
    },
}
