define story = Character(None)
define system = Character("System", color="#c9d6ff")

define oren = Character("Oren", color="#f0c36a")
define inner_voice = Character("Voice", color="#f4f0ff", what_italic=True)
define jotunn = Character("Jötunn", color="#f4f0ff", what_italic=True)
define embrum = Character("Embrum", color="#9ed0ff")
define guard = Character("Village Guard", color="#d7d0b5")
define villager = Character("Villager", color="#bee6b1")
define chief = Character("Village Chief", color="#f1d5a8")
define mayor = Character("Village Mayor", color="#f1d5a8")
define wizard = Character("Traveling Wizard", color="#d4b6ff")
define eldran_merchant = Character("Eldran Merchant", color="#d8c3ff")
define miner = Character("Miner", color="#d0c4aa")
define foreman = Character("Mine Foreman", color="#e0b98a")
define water_worker = Character("Water Worker", color="#9bc7e6")
define medic = Character("Medic-Cleric", color="#d9e6c4")
define drunk_father = Character("Drunk Man", color="#d8b28a")
define village_woman = Character("Village Woman", color="#c7dfc5")
define village_daughter = Character("Village Girl", color="#d7c5e8")
define wounded_miner = Character("Wounded Miner", color="#d0a58f")
define enemy = Character("Enemy", color="#ffb0a8")
